#ifndef _ROSE_K_P_ETHERNET_H
#define _ROSE_K_P_ETHERNET_H

#define ETHERNET_BASE	    0xFD580000
#define ETHERNET_MDIO	    (ETHERNET_BASE + 0x0E14)
#define ETHERNET_MDIO_END	(ETHERNET_BASE + 0x0E1B)
#define ETHERNET_END	    (ETHERNET_BASE + 0xFFFF)

#endif /*_ROSE_K_P_ETHERNET_H */
