#ifndef _ROSE_C_HelloWorld_H
#define _ROSE_C_HelloWorld_H

#include "common/screen.h"

#define STARTX 20
#define STARTY 10

void draw_hello_world () {
    printf ("\n");
    printf ("\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf (" ");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("e");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("e");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf ("r");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("e");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("r");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf ("H");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (",");
    printf (",");
    printf (",");
    printf (",");
    printf (",");
    printf (",");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf (",");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (",");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("H");
    printf (" ");
    printf (" ");
    printf ("e");
    printf ("e");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("e");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (",");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (",");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf (":");
    printf (":");
    printf (":");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf ("o");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf ("r");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("l");
    printf (" ");
    printf (" ");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("d");
    printf ("d");
    printf (":");
    printf (":");
    printf (":");
    printf (":");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf ("H");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf ("e");
    printf (" ");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (",");
    printf (":");
    printf (":");
    printf (":");
    printf (",");
    printf (",");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf ("W");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("W");
    printf ("W");
    printf ("W");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf ("o");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf ("r");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf ("l");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("d");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (",");
    printf (":");
    printf (":");
    printf (":");
    printf (",");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("\r\n");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (",");
    printf (",");
    printf (",");
    printf (",");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf (" ");
    printf ("\r\n");
}

#endif //_ROSE_C_HelloWorld_H

/* Copyright (C) 2020 Aaron Alef */
